import express from "express";
import asyncHandler from "../utils/asyncHandler.js";
import { login, memberLogin, requestMemberOtp, requestPasswordReset, resetPassword, setMemberPassword } from "../controllers/authController.js";
const router = express.Router();
router.post("/login", asyncHandler(login));
router.post("/member/request-otp", asyncHandler(requestMemberOtp));
router.post("/member/set-password", asyncHandler(setMemberPassword));
router.post("/member/login", asyncHandler(memberLogin));
router.post("/password/request-reset", asyncHandler(requestPasswordReset));
router.post("/password/reset", asyncHandler(resetPassword));
export default router;
